apiVersion: v1
kind: Service
metadata:
  namespace: nxs
  name: nxs-api-servers-svc
  annotations:
   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
  selector:
    name: nxs-api-servers-svc
