apiVersion: batch/v1
kind: Job
metadata:
  name: vc-worker
  namespace: nxs
spec:
  template:
    spec:
      containers:
      - name: vc-job
        image: ossnxs.azurecr.io/vc_worker:v0.1.1
        command: ["/bin/bash", "apps/vehicle_counting/scripts/run_worker.sh"]
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 1
            memory: "2Gi"
          limits:
            cpu: 1.5
            memory: "3Gi"
        env:
        - name: VIDEO_UUID
          value: ""
        - name: DEBUG
          value: "false"
        - name: NXS_URL
          valueFrom:
            configMapKeyRef:
              name: vc-config
              key: NXS_URL
        - name: NXS_API_KEY
          valueFrom:
            configMapKeyRef:
              name: vc-config
              key: NXS_API_KEY
        - name: VC_BLOBSTORE_CONN_STR
          valueFrom:
            configMapKeyRef:
              name: vc-config
              key: VC_BLOBSTORE_CONN_STR
        - name: VC_BLOBSTORE_CONTAINER_NAME
          valueFrom:
            configMapKeyRef:
              name: vc-config
              key: VC_BLOBSTORE_CONTAINER_NAME
        - name: VC_COSMOSDB_CONN_STR
          valueFrom:
            configMapKeyRef:
              name: vc-config
              key: VC_COSMOSDB_CONN_STR
        - name: VC_COSMOSDB_NAME
          valueFrom:
            configMapKeyRef:
              name: vc-config
              key: VC_COSMOSDB_NAME
        - name: VC_DETECTOR_UUID
          valueFrom:
            configMapKeyRef:
              name: vc-config
              key: VC_DETECTOR_UUID
        - name: VC_TRACKER_UUID
          valueFrom:
            configMapKeyRef:
              name: vc-config
              key: VC_TRACKER_UUID
        - name: VC_REPORT_INTERVAL_SECS
          valueFrom:
            configMapKeyRef:
              name: vc-config
              key: VC_REPORT_INTERVAL_SECS   
      imagePullSecrets:
      - name: regcred
      restartPolicy: Never
      nodeSelector:
        restype: cpu
