apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nxsapp
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 250Gi