apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: redis-standalone
  namespace: ot-operators
spec:
  redisConfig:
    additionalRedisConfig: redis-external-config
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: ${CPU_REQUEST}
        memory: ${MEMORY_REQUEST}
      # limits:
      #   cpu: ${CPU_REQUEST}
      #   memory: ${MEMORY_REQUEST}
  # storage:
  #   volumeClaimTemplate:
  #     spec:
  #       # storageClassName: standard
  #       accessModes: ["ReadWriteOnce"]
  #       resources:
  #         requests:
  #           storage: ${MEMORY_REQUEST}
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:1.0
  nodeSelector:
    restype: cpu